language: objective-c
osx_image: xcode7.1
before_install:
  - brew update
  - brew upgrade xctool
  - brew install carthage
script:
  - xcodebuild -project Osusume.xcodeproj -scheme "Osusume" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.2,name=iPhone 6" test
